version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  reasoner:
    image: eyereasoner/reasoning-service
    ports:
      - "8888:80"
    environment:
      MODE: "development"
      STACK_LIMIT: "10G"
      TIMEOUT: "300"
    volumes:
      - .:/app
      - ./config:/config
      - ./temp:/tmp
